version: 2
updates:
  # version and security updates for the root application
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # version and security updates for the example application
  - package-ecosystem: "npm"
    directory: "/example-app"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"