name: Publish Changelog

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run publish command
        run: npm run ccg publish

        # what should this be?
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"

      # use whats in the sprint release script
      - name: Commit changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"

      - name: Push changes
        run: |
          git push origin main

      - name: Tag the commit
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')
          TAG_NAME="release-$TIMESTAMP"
          git tag $TAG_NAME
          git push origin $TAG_NAME
